Clear up the README for the new user
Nixtla/mlforecast pull request #397
Opened 2024-08-10 02:46 UTC by Ammar-Azman

## Description

I am facing a problem of using the library which I don't understand what is the format required by the package
before I can pass it to the model. Hence, I added some note so it could be easier for other new user.

Checklist:
- [x] This PR has a meaningful title and a clear description.
- [x] The tests pass.
- [x] All linting tasks pass.
- [x] The notebooks are clean.

2024-08-10 02:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Nixtla/mlforecast?pullRequest=397) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Nixtla/mlforecast?pullRequest=397) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Nixtla/mlforecast?pullRequest=397) it.</sub>

2024-08-12 16:30 UTC, jmoralez requested changes
Thanks! Please also make this change in nbs/index.ipynb

2024-08-12 16:30 UTC, jmoralez commented on README.md
> +> Note: The unique_id serves as an identifier for each distinct time series in your dataset. If you are using only single time series from your dataset, just create a single id number for this column
```suggestion
> Note: The unique_id serves as an identifier for each distinct time series in your dataset. If you are using only single time series from your dataset, set this column to a constant value.
```

2024-08-14 07:51 UTC, Ammar-Azman commented
> Thanks! Please also make this change in nbs/index.ipynb

Okay done.

2024-08-14 16:01 UTC, jmoralez commented
Thanks!

2024-08-14 16:02 UTC, merged